# Generated by Django 4.0.4 on 2022-05-03 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'news_tag',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.CharField(max_length=5000)),
                ('pub_date', models.DateField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.newstag')),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
