# Generated by Django 4.0.4 on 2022-05-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vsl_seq', models.CharField(max_length=6)),
                ('so_no', models.CharField(max_length=4)),
                ('cntrno', models.CharField(max_length=11)),
                ('vsl_cd', models.CharField(max_length=4)),
                ('voyage', models.CharField(max_length=11)),
                ('cntr_sz', models.CharField(max_length=2)),
                ('erase_date', models.CharField(default=0, max_length=14)),
                ('in_date', models.DateTimeField()),
                ('out_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'import',
                'unique_together': {('vsl_seq', 'so_no', 'cntrno')},
            },
        ),
        migrations.CreateModel(
            name='Exp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vsl_seq', models.CharField(max_length=6)),
                ('so_no', models.CharField(max_length=4)),
                ('cntrno', models.CharField(max_length=11)),
                ('vsl_cd', models.CharField(max_length=4)),
                ('voyage', models.CharField(max_length=11)),
                ('cntr_sz', models.CharField(max_length=2)),
                ('erase_date', models.CharField(default=0, max_length=14)),
                ('in_date', models.DateTimeField()),
                ('ship_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'export',
                'unique_together': {('vsl_seq', 'so_no', 'cntrno')},
            },
        ),
        migrations.CreateModel(
            name='Cntr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cntrno', models.CharField(max_length=11)),
                ('op_date', models.DateTimeField()),
                ('op_cd', models.CharField(max_length=1)),
                ('stus_cd', models.CharField(max_length=2)),
                ('vsl_cd', models.CharField(max_length=4)),
                ('voyage', models.CharField(max_length=11)),
                ('so_no', models.CharField(max_length=4)),
                ('pol', models.CharField(max_length=5)),
                ('pod', models.CharField(max_length=5)),
                ('seal_no', models.CharField(max_length=10)),
                ('line_seal', models.CharField(max_length=15)),
                ('vsl_seq', models.CharField(max_length=6)),
                ('goss_wt', models.CharField(max_length=9)),
                ('tare_wt', models.CharField(max_length=4)),
                ('truk_wt', models.CharField(max_length=5)),
                ('wt', models.CharField(max_length=9)),
                ('truk_nm', models.CharField(max_length=20)),
                ('truk_no', models.CharField(max_length=7)),
                ('tran_pgm_id', models.CharField(max_length=20)),
                ('owner', models.CharField(max_length=4)),
                ('cntr_sz', models.CharField(max_length=2)),
                ('erase_date', models.CharField(default=0, max_length=14)),
            ],
            options={
                'db_table': 'cntr',
                'unique_together': {('vsl_seq', 'cntrno')},
            },
        ),
    ]
